version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/python.dockerfile
      args:
        - BUILD_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
#    depends_on:
#      - db